apiVersion: v1
kind: Service
metadata:
  name: db-writer
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: db-writer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-writer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-writer
  template:
    metadata:
      labels:
        app: db-writer
    spec:
      containers:
        - name: db-writer
          image: mysql:latest
          env:
            - name: MYSQL_USER
              value: root
            - name: mysql_PASSWORD
              value: password
            - name: POSTGRES_DB
              value: students
