---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
spec:
  capacity:
    storage: 5Gi  # Adjust storage as needed
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data  # Path on the host where data is stored

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Match this with the PV storage size

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment  # Updated name for clarity
spec:
  selector:
    matchLabels:
      app: mysql  # Updated to match Service selector
  template:
    metadata:
      labels:
        app: mysql  # Updated to match Service selector
    spec:
      containers:
        - name: database
          image: rajatrokde/k-8-db  # Replace with your actual DB image
          ports:
            - containerPort: 3306  # Exposing MySQL port
          volumeMounts:
            - mountPath: /data/db  # Path inside the container for DB data
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql  # Matching the Deployment label
  ports:
    - port: 3306
      targetPort: 3306
  # Uncomment the following line if you want external access
  # type: NodePort
