apiVersion: apps/v1
kind: Deployment
metadata:
  name: raj-deployment
spec:
  replicas: 1  # Number of pod replicas
  selector:
    matchLabels:
      app: raj
  strategy:
    type: RollingUpdate  # Rollout strategy
    rollingUpdate:
      maxUnavailable: 1   # Max unavailable pods during the update
      maxSurge: 1         # Max pods created above the desired replicas during the update
  template:
    metadata:
      labels:
        app: raj
    spec:
      containers:
        - name: raj
          image: rajatrokde/php-db  # Docker image
          ports:
            - containerPort: 80
          resources: {}
