apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  type: NodePort  # To expose the service via NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Ensure this is within the 30000-32767 range

