name: Docker CI/CD

on:
  push:
    branches:
      - main  # Trigger on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=rajatrokde/k-8-fe:${{ github.sha }}  # Use commit SHA for unique tag
          docker build -t $IMAGE_TAG .
          docker images  # List built images for debugging
          docker push $IMAGE_TAG
