name: Docker CI/CD

on:
  push:
    branches:
      - main  # Changes this to the branch you want to trigger the CI/CD pipeline on
      #- master # Changes this to the branch you want to trigger the CI/CD pipeline on

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          # Use a Docker access token if preferred instead of a password.

      - name: Build and push Docker image
        run: |
          docker build -t rajatrokde/k-8-fe:v1 .
          docker push rajatrokde/k-8-fe:v1

     
